from PIL import Image
import streamlit as st
from streamlit_image_coordinates import streamlit_image_coordinates

import subprocess

# Path to the image generated by your CLI tool

st.title("Black Hole Ray Tracer: Click Tracker")

if "image_version" not in st.session_state:
    st.session_state.image_version = 0
# 1. Display the image and capture click data
# 'value' will be a dictionary like {'x': 250, 'y': 150} or None
IMAGE_PATH = f"./web_images/blackhole_cli.png"
img=Image.open(IMAGE_PATH)
value = streamlit_image_coordinates(img, key=f"iamge_{st.session_state.image_version}")

kepernyoSZELES_def = 2147483648//2
SZELES=640
MAGAS=320
if "prec_prev" not in st.session_state:
    st.session_state.prec_prev = False
if "prec_double" not in st.session_state:
    st.session_state.prec_double = False
if "click_count" not in st.session_state:
    st.session_state.click_count = 0
if "kepernyoSZELES" not in st.session_state:
    st.session_state.kepernyoSZELES = kepernyoSZELES_def
if "kepernyoMAGAS" not in st.session_state:
    st.session_state.kepernyoMAGAS  = kepernyoSZELES_def//2
if "SZELES" not in st.session_state:
    st.session_state.SZELES = 640
if "MAGAS" not in st.session_state:
    st.session_state.MAGAS  = 320
if "ikezd" not in st.session_state:
    st.session_state.ikezd=0
if "jkezd" not in st.session_state:
    st.session_state.jkezd=0
if "iveg" not in st.session_state:
    st.session_state.iveg=kepernyoSZELES_def
if "subkepernyoSZELES" not in st.session_state:
    st.session_state.subkepernyoSZELES=kepernyoSZELES_def

st.success(f"ikezd={st.session_state.ikezd}, jkezd={st.session_state.jkezd}, iveg={st.session_state.iveg}")

st.checkbox(
    "🔬 Use double precision",
    key="prec_double"
)

if st.session_state.prec_double == True:
    prec_str = "--double"
else:
    prec_str = "--float"

if st.session_state.prec_double != st.session_state.prec_prev:
    st.session_state.prec_prev = st.session_state.prec_double
    subprocess.run(["./main", "--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--kepernyoSZELES", str(st.session_state.kepernyoSZELES), "--kepernyoMAGAS", str(st.session_state.kepernyoMAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg), prec_str ])
    subprocess.run(["python", "cli_imagemaker.py"])
    st.session_state.image_version += 1
    st.rerun()


if st.button("🔄 Reset view"):
    kepernyoSZELES = kepernyoSZELES_def
    kepernyoMAGAS  = kepernyoSZELES_def//2
    SZELES = 640
    MAGAS  = 320
    st.session_state.iveg=kepernyoSZELES_def
    st.session_state.ikezd=0
    st.session_state.jkezd=0
    st.session_state.subkepernyoSZELES=kepernyoSZELES_def
    subprocess.run(["./main"])
    #subprocess.run(["./main", "--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--kepernyoSZELES", str(st.session_state.kepernyoSZELES), "--kepernyoMAGAS", str(st.session_state.kepernyoMAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg)])
    subprocess.run(["python", "cli_imagemaker.py"])  
    st.session_state.image_version += 1
    st.success("View reset")
    st.rerun()

if st.button("🧮 Double vs Float view"):
    kepernyoSZELES = kepernyoSZELES_def
    kepernyoMAGAS  = kepernyoSZELES_def//2
    SZELES = 640
    MAGAS  = 320
    st.session_state.iveg=451518464
    st.session_state.ikezd=451517952
    st.session_state.jkezd=206130944
    subprocess.run(["./main", "--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--kepernyoSZELES", str(st.session_state.kepernyoSZELES), "--kepernyoMAGAS", str(st.session_state.kepernyoMAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg), prec_str ])
    subprocess.run(["python", "cli_imagemaker.py"])
    st.session_state.image_version += 1
    st.success("View reset")
    st.rerun()

if value:
    # 2. Extract relative coordinates
    click_x = value["x"] #SZELES
    click_y = value["y"]
    if click_x < SZELES//3:
        st.session_state.iveg=st.session_state.ikezd+st.session_state.subkepernyoSZELES//2
    elif click_x < 2*SZELES//3:
        st.session_state.iveg=st.session_state.ikezd+3*st.session_state.subkepernyoSZELES//4
        st.session_state.ikezd=st.session_state.ikezd+st.session_state.subkepernyoSZELES//4
    else:
        st.session_state.iveg=st.session_state.ikezd+st.session_state.subkepernyoSZELES
        st.session_state.ikezd=st.session_state.ikezd+st.session_state.subkepernyoSZELES//2
    if click_y < MAGAS//3:
        None
    elif click_y < 2*MAGAS//3:
        st.session_state.jkezd=st.session_state.jkezd+st.session_state.subkepernyoSZELES//8
    else:
        st.session_state.jkezd=st.session_state.jkezd+st.session_state.subkepernyoSZELES//4
        
    st.session_state.subkepernyoSZELES=st.session_state.subkepernyoSZELES//2

    
    st.success(f"User clicked at: X={click_x}, Y={click_y}, ikezd={st.session_state.ikezd}, jkezd={st.session_state.jkezd}, iveg={st.session_state.iveg}")
    
    if st.session_state.prec_double == True:
        prec_str = "--double"
    else:
        prec_str = "--float"
    #subprocess.run(["./main", "--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg)])
    subprocess.run(["./main", "--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--kepernyoSZELES", str(st.session_state.kepernyoSZELES), "--kepernyoMAGAS", str(st.session_state.kepernyoMAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg), prec_str ])
    subprocess.run(["python", "cli_imagemaker.py"])
    st.session_state.image_version += 1
    st.rerun()
    # You can now pass these integers directly to your CLI tool
    # subprocess.run(["./your_cli", "--x", str(click_x), "--y", str(click_y)])
else:
    st.info("Click anywhere on the image to track coordinates.")

