from PIL import Image
import streamlit as st
from streamlit_image_coordinates import streamlit_image_coordinates

import subprocess

import hashlib
import json
import sqlite3
import shutil
from pathlib import Path

import cv2
from skimage.measure import shannon_entropy

import numpy as np

# =========================
# Paths
# =========================

TEMP_IMAGE = Path("./web_images/blackhole_cli.png")
CACHE_DIR = Path("./cache")
CACHE_IMG_DIR = CACHE_DIR / "images"
CACHE_DB = CACHE_DIR / "cache.db"

CACHE_IMG_DIR.mkdir(parents=True, exist_ok=True)

def init_cache_db():
    with sqlite3.connect(CACHE_DB) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS renders (
                hash TEXT PRIMARY KEY,
                image_path TEXT NOT NULL
            )
        """)
def cache_lookup(h):
    with sqlite3.connect(CACHE_DB) as conn:
        row = conn.execute(
            "SELECT image_path FROM renders WHERE hash = ?",
            (h,)
        ).fetchone()
    return row[0] if row else None

def cache_store(h, image_path):
    with sqlite3.connect(CACHE_DB) as conn:
        conn.execute(
            "INSERT OR REPLACE INTO renders (hash, image_path) VALUES (?, ?)",
            (h, image_path)
        )

init_cache_db()

def render_hash(params: dict) -> str:
    key = json.dumps(params, sort_keys=True)
    return hashlib.sha256(key.encode()).hexdigest()

# Path to the image generated by your CLI tool

st.title("Black Hole Ray Tracer: Click Tracker")

if "image_version" not in st.session_state:
    st.session_state.image_version = 0
# 1. Display the image and capture click data
# 'value' will be a dictionary like {'x': 250, 'y': 150} or None
de0_def=0.01
errormax_def=0.001
kepernyoSZELES_def = 2147483648*8
SZELES=640
MAGAS=320
if "prec_prev" not in st.session_state:
    st.session_state.prec_prev = False
if "prec_double" not in st.session_state:
    st.session_state.prec_double = False
if "click_count" not in st.session_state:
    st.session_state.click_count = 0
if "kepernyoSZELES" not in st.session_state:
    st.session_state.kepernyoSZELES = kepernyoSZELES_def
if "kepernyoMAGAS" not in st.session_state:
    st.session_state.kepernyoMAGAS  = kepernyoSZELES_def//2
if "SZELES" not in st.session_state:
    st.session_state.SZELES = 640
if "MAGAS" not in st.session_state:
    st.session_state.MAGAS  = 320
if "ikezd" not in st.session_state:
    st.session_state.ikezd=0
if "jkezd" not in st.session_state:
    st.session_state.jkezd=0
if "iveg" not in st.session_state:
    st.session_state.iveg=kepernyoSZELES_def
if "subkepernyoSZELES" not in st.session_state:
    st.session_state.subkepernyoSZELES=kepernyoSZELES_def
if "errormax" not in st.session_state:
    st.session_state.errormax = errormax_def
if "de0" not in st.session_state:
    st.session_state.de0 = de0_def
if "fast" not in st.session_state:
    st.session_state.fast = True 
if "rs" not in st.session_state:
    st.session_state.rs=0.05
if "a" not in st.session_state:
    st.session_state.a = 0.0
if "fast_spining" not in st.session_state:
    st.session_state.fast_spining=False
if "Q" not in st.session_state:
    st.session_state.Q=0.0

if st.session_state.prec_double == True:
    prec_str = "--double"
else:
    prec_str = "--float"
if st.session_state.fast == True:
    st.session_state.de0=de0_def
    st.session_state.errormax=errormax_def
else:
    st.session_state.de0=0.0001
    st.session_state.errormax=0.000001
if st.session_state.fast_spining==False:
    st.session_state.a=0.0
else:
    st.session_state.a=st.session_state.rs/2-0.001

render_params = {
        "SZELES": st.session_state.SZELES,
        "MAGAS": st.session_state.MAGAS,
        "kepernyoSZELES": st.session_state.kepernyoSZELES,
        "kepernyoMAGAS": st.session_state.kepernyoMAGAS,
        "ikezd": st.session_state.ikezd,
        "jkezd": st.session_state.jkezd,
        "iveg": st.session_state.iveg,
        "precision": "double" if st.session_state.prec_double else "float",
        "de0" : st.session_state.de0,
        "errormax" : st.session_state.errormax,
        "rs" : st.session_state.rs,
        "a" : st.session_state.a,
        "Q" : st.session_state.Q
}

h = render_hash(render_params)
cached_image = cache_lookup(h)

IMAGE_PATH = f"./web_images/blackhole_cli.png"
if cached_image and Path(cached_image).exists():
    IMAGE_PATH = cached_image
    st.info("📦 Cache hit – image loaded from disk")
else:
    subprocess.run(["./main", "--a", str(st.session_state.a),"--rs",str(st.session_state.rs), "--Q", str(st.session_state.Q), "--de0", str(st.session_state.de0), "--errormax", str(st.session_state.errormax),"--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--kepernyoSZELES", str(st.session_state.kepernyoSZELES), "--kepernyoMAGAS", str(st.session_state.kepernyoMAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg), prec_str ])
    subprocess.run(["python", "cli_imagemaker.py"])
    IMAGE_PATH = f"./web_images/blackhole_cli.png"
    cached_path = CACHE_IMG_DIR / f"{h}.png"
    shutil.copy(IMAGE_PATH, cached_path)
    cache_store(h, str(cached_path))
img=Image.open(IMAGE_PATH)
st.success(str(IMAGE_PATH))
value = streamlit_image_coordinates(img, key=f"iamge_{st.session_state.image_version}")

img_cv = cv2.imread(IMAGE_PATH)
gray = cv2.cvtColor(img_cv, cv2.COLOR_RGB2GRAY)
entropy_value = shannon_entropy(gray)
variance = float(np.var(gray))*0.2/255.0
edges = cv2.Canny(gray, 50, 150)
edge_density = edges.mean()
st.success(f"Shannon entropy: {entropy_value}, Variance: {variance}, Edge density: {edge_density}")
st.success(f"ikezd={st.session_state.ikezd}, jkezd={st.session_state.jkezd}, iveg={st.session_state.iveg}")

st.checkbox(
    "🔬 Use double precision",
    key="prec_double"
)
st.checkbox(
    "⚡ Fast mode — reduces runtime by using larger steps ⚡",
    key="fast"
)
st.checkbox(
    "🌀 Critically spinning black hole",
    key="fast_spining"
)


if st.button("🔄 Reset view"):
    kepernyoSZELES = kepernyoSZELES_def
    kepernyoMAGAS  = kepernyoSZELES_def//2
    SZELES = 640
    MAGAS  = 320
    st.session_state.iveg=kepernyoSZELES_def
    st.session_state.ikezd=0
    st.session_state.jkezd=0
    st.session_state.subkepernyoSZELES=kepernyoSZELES_def
    #subprocess.run(["./main"])
    #subprocess.run(["./main", "--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--kepernyoSZELES", str(st.session_state.kepernyoSZELES), "--kepernyoMAGAS", str(st.session_state.kepernyoMAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg)])
    #subprocess.run(["python", "cli_imagemaker.py"])  
    st.session_state.image_version += 1
    st.success("View reset")
    st.rerun()

if st.button("🧮 Double vs Float view"):
    kepernyoSZELES = kepernyoSZELES_def
    kepernyoMAGAS  = kepernyoSZELES_def//2
    SZELES = 640
    MAGAS  = 320
    #maski jo seed: ikezd=536608768, jkezd=162267136, iveg=537133056
    st.session_state.iveg=451518464
    st.session_state.ikezd=451517952
    st.session_state.jkezd=206130944
   # subprocess.run(["./main", "--SZELES", str(SZELES), "--MAGAS", str(MAGAS), "--kepernyoSZELES", str(st.session_state.kepernyoSZELES), "--kepernyoMAGAS", str(st.session_state.kepernyoMAGAS), "--ikezd", str(st.session_state.ikezd), "--jkezd", str(st.session_state.jkezd), "--iveg", str(st.session_state.iveg), prec_str ])
    #subprocess.run(["python", "cli_imagemaker.py"])
    #st.session_state.image_version += 1
    st.success("View reset")
    st.rerun()

if value:
    # 2. Extract relative coordinates
    click_x = value["x"] #SZELES
    click_y = value["y"]
    if click_x < SZELES//3:
        st.session_state.iveg=st.session_state.ikezd+st.session_state.subkepernyoSZELES//2
    elif click_x < 2*SZELES//3:
        st.session_state.iveg=st.session_state.ikezd+3*st.session_state.subkepernyoSZELES//4
        st.session_state.ikezd=st.session_state.ikezd+st.session_state.subkepernyoSZELES//4
    else:
        st.session_state.iveg=st.session_state.ikezd+st.session_state.subkepernyoSZELES
        st.session_state.ikezd=st.session_state.ikezd+st.session_state.subkepernyoSZELES//2
    if click_y < MAGAS//3:
        None
    elif click_y < 2*MAGAS//3:
        st.session_state.jkezd=st.session_state.jkezd+st.session_state.subkepernyoSZELES//8
    else:
        st.session_state.jkezd=st.session_state.jkezd+st.session_state.subkepernyoSZELES//4
        
    st.session_state.subkepernyoSZELES=st.session_state.subkepernyoSZELES//2

    
    st.success(f"User clicked at: X={click_x}, Y={click_y}, ikezd={st.session_state.ikezd}, jkezd={st.session_state.jkezd}, iveg={st.session_state.iveg}")
    
    if st.session_state.prec_double == True:
        prec_str = "--double"
    else:
        prec_str = "--float"
    st.session_state.image_version += 1
    st.rerun()
    # You can now pass these integers directly to your CLI tool
    # subprocess.run(["./your_cli", "--x", str(click_x), "--y", str(click_y)])
else:
    st.info("Click anywhere on the image to track coordinates.")
