"""Deciding whether a trigonometric rational expression is identically zero.

`sympy.simplify` is a heuristic: on a Kerr-Newman-sized expression it can run for
many minutes, and it can fail to reach 0 even when the identity holds, which
would surface as a spurious REFUTED.  For the expressions this pipeline produces
there is an exact decision procedure instead.

Every expression here is a rational function of the coordinates, the parameters,
the velocities, and the sines and cosines of the angular coordinates.  Introduce
a symbol for each sine and cosine and it becomes an honest rational function; the
only thing lost is the relation s^2 + c^2 = 1.  So:

    1. expand multiple angles (sin(4x) and friends) into powers of sin x, cos x;
    2. replace sin(u) -> s_u and cos(u) -> c_u;
    3. take the numerator of the resulting rational function;
    4. reduce it modulo the ideal generated by the {s_u^2 + c_u^2 - 1}.

A zero remainder proves the original expression vanishes identically: polynomial
reduction is exact and terminating, with none of simplify's heuristics.
"""

from __future__ import annotations

import random
import signal

import sympy as sp

from ..normalize import rewrite_trig_ratios


class _Budget:
    """Wall-clock budget, so one pathological metric cannot wedge the whole run."""

    def __init__(self, seconds):
        self.seconds = seconds

    def __enter__(self):
        if self.seconds:
            signal.signal(signal.SIGALRM, self._fire)
            signal.alarm(int(self.seconds))
        return self

    def __exit__(self, *exc):
        signal.alarm(0)
        return False

    @staticmethod
    def _fire(signum, frame):
        raise TimeoutError("budget exhausted")


def schwartz_zippel(expr, trials=24, spread=10**6, seed=0) -> bool:
    """Exact probabilistic identity test.

    Everything is evaluated in exact rational arithmetic - no floating point
    anywhere - so a non-zero result is a definitive refutation, never a rounding
    artefact.

    The subtlety is the angles.  Substituting a random rational for theta leaves
    sin(1234/5678) behind, which exact arithmetic cannot decide.  Instead the
    expression is first rewritten in terms of symbols s and c for each sine and
    cosine, and those are given random *rational points on the unit circle* via
    the Weierstrass substitution

        s = 2t/(1 + t^2),   c = (1 - t^2)/(1 + t^2),   s^2 + c^2 = 1 exactly

    for a random rational t.  So the sample respects the one relation that ties
    the sines and cosines together, and every evaluation is a rational number.

    By the Schwartz-Zippel lemma a non-zero rational function of total degree d
    vanishes at a random point of a finite set S with probability at most d/|S|.
    With |S| = `spread` and `trials` independent points, the chance of a false
    "looks zero" verdict is at most (d/|S|)^trials - far below every other source
    of error in the pipeline.  It is still not a proof, and callers say so.
    """
    poly, _rels = trig_to_polynomial(expr)
    syms = sorted(poly.free_symbols, key=sp.default_sort_key)
    if not syms:
        return sp.simplify(poly) == 0

    rng = random.Random(seed)
    circle = {}
    for s_ in syms:
        name = str(s_)
        if name.startswith("__s") or name.startswith("__c"):
            circle.setdefault(name[3:], None)

    for _ in range(trials):
        point = {}
        for k in circle:
            t = sp.Rational(rng.randrange(1, spread), rng.randrange(1, spread))
            point[sp.Symbol(f"__s{k}", real=True)] = 2 * t / (1 + t**2)
            point[sp.Symbol(f"__c{k}", real=True)] = (1 - t**2) / (1 + t**2)
        for s_ in syms:
            if s_ not in point:
                point[s_] = sp.Rational(rng.randrange(1, spread), rng.randrange(1, spread))
        try:
            val = sp.cancel(sp.together(poly.xreplace(point)))
        except Exception:
            return False
        if val != 0:
            return False
    return True


def _angle_arguments(expr):
    """Every distinct argument appearing under a sin or a cos."""
    return sorted({f.args[0] for f in expr.atoms(sp.sin, sp.cos)},
                  key=sp.default_sort_key)


def trig_to_polynomial(expr):
    """Return (polynomial-ready expression, the s^2+c^2-1 relations)."""
    # tan/cot/sec/csc first, or they survive the sin/cos substitution and leave a
    # transcendental of a rational argument that exact arithmetic cannot decide.
    expr = sp.expand_trig(rewrite_trig_ratios(expr))
    subs, rels = {}, []
    for k, u in enumerate(_angle_arguments(expr)):
        s = sp.Symbol(f"__s{k}", real=True)
        c = sp.Symbol(f"__c{k}", real=True)
        subs[sp.sin(u)] = s
        subs[sp.cos(u)] = c
        rels.append(s**2 + c**2 - 1)
    return expr.xreplace(subs), rels


def is_identically_zero(expr, budget_seconds=600):
    """Decide expr == 0.  Returns (verdict, method).

    Strategies, strongest first, each under a wall-clock budget:

    1. rational normal form, then reduction modulo sin^2 + cos^2 - 1 - exact,
       complete, and the one that yields an actual proof;
    2. `simplify`, for expressions carrying square roots (the tetrad);
    3. exact-rational Schwartz-Zippel - probabilistic, but quantified.

    A cheap Schwartz-Zippel screen runs first regardless: a genuinely non-zero
    expression is refuted in milliseconds instead of after a fruitless reduction.
    """
    expr = sp.sympify(expr)
    if expr == 0:
        return True, "syntactic"

    if not schwartz_zippel(expr, trials=4):
        return False, "refuted at a random rational point (exact arithmetic)"

    try:
        with _Budget(budget_seconds):
            poly, rels = trig_to_polynomial(expr)
            num, _den = sp.together(poly).as_numer_denom()
            num = sp.expand(num)
            if num == 0:
                return True, "rational normal form"
            if rels:
                free = sorted(num.free_symbols, key=sp.default_sort_key)
                _, rem = sp.reduced(num, rels, *free, order="lex")
                if sp.expand(rem) == 0:
                    return True, "polynomial reduction mod sin^2+cos^2-1"
    except (sp.PolynomialError, TimeoutError, NotImplementedError, ValueError):
        pass

    try:
        with _Budget(max(1, budget_seconds // 3)):
            if sp.simplify(expr) == 0:
                return True, "simplify"
    except TimeoutError:
        pass

    return (schwartz_zippel(expr, trials=24),
            "Schwartz-Zippel, 24 exact rational points (probabilistic)")


def all_zero(residuals):
    """Decide a list or matrix of residuals; returns (verdict, method, first_bad)."""
    method = "syntactic"
    for e in list(residuals):
        ok, m = is_identically_zero(e)
        if m != "syntactic":
            method = m
        if not ok:
            return False, method, e
    return True, method, None
